'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4971
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class Search

	'''<summary>
	'''form1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

	'''<summary>
	'''LoginName1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents LoginName1 As Global.System.Web.UI.WebControls.LoginName

	'''<summary>
	'''lnkEditMyProfile control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lnkEditMyProfile As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''lnkAddUser control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lnkAddUser As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''lnkLogout control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lnkLogout As Global.System.Web.UI.WebControls.LinkButton

	'''<summary>
	'''txtUserName control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtUserName As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''txtDepartment control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtDepartment As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''txtFirstName control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtFirstName As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''txtProject control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtProject As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''txtLastName control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtLastName As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''txtMobile control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtMobile As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''txtEmail control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtEmail As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''txtOfficeAddress control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtOfficeAddress As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''btnSearch control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents btnSearch As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''gv control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents gv As Global.System.Web.UI.WebControls.GridView
End Class
